server:
  port: 6001

spring:
  application:
    name: cloud-6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
    register-with-eureka: true
    fetch-registry: true