server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YouTuker/springcloud-config
          search-paths:
            - springcloud-config
          username: yct20210715@163.com
          password: yct199318..
      label: master


# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
    register-with-eureka: true
    fetch-registry: true

