server:
  port: 8001
spring:
  application:
    name: comsurs
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  management:
    endpoint:
      web:
        exposure:
          incloud: '*'
