server:
  port: 7002


eureka:
  instance:
    hostname: eurek-server-7002
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
spring:
  application:
    name: eureka-server-7002
