server:
  port: 7003

eureka:
  instance:
    hostname: eurek-server-7003
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
spring:
  application:
    name: cloud-eureka-server-7003